// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBDvgMgw1Yyx18mtlo_rfoX6b80R6tkFs',
    appId: '1:132546231666:web:47631dc794c172e9f571eb',
    messagingSenderId: '132546231666',
    projectId: 'nyxnyx-3ee69',
    authDomain: 'nyxnyx-3ee69.firebaseapp.com',
    storageBucket: 'nyxnyx-3ee69.appspot.com',
    measurementId: 'G-5XTM2EX8RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRvZzyDTakbsLprlv2CP_FdPIE5czMRY',
    appId: '1:132546231666:android:67846007ca8f1275f571eb',
    messagingSenderId: '132546231666',
    projectId: 'nyxnyx-3ee69',
    storageBucket: 'nyxnyx-3ee69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn4diUJHjvLbPdvpvmLp7yu1Me51HNDFo',
    appId: '1:132546231666:ios:7cbb4b3c9b8c5d2cf571eb',
    messagingSenderId: '132546231666',
    projectId: 'nyxnyx-3ee69',
    storageBucket: 'nyxnyx-3ee69.appspot.com',
    iosBundleId: 'com.example.estbm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn4diUJHjvLbPdvpvmLp7yu1Me51HNDFo',
    appId: '1:132546231666:ios:7cbb4b3c9b8c5d2cf571eb',
    messagingSenderId: '132546231666',
    projectId: 'nyxnyx-3ee69',
    storageBucket: 'nyxnyx-3ee69.appspot.com',
    iosBundleId: 'com.example.estbm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBDvgMgw1Yyx18mtlo_rfoX6b80R6tkFs',
    appId: '1:132546231666:web:674483e6dd7ed4f7f571eb',
    messagingSenderId: '132546231666',
    projectId: 'nyxnyx-3ee69',
    authDomain: 'nyxnyx-3ee69.firebaseapp.com',
    storageBucket: 'nyxnyx-3ee69.appspot.com',
    measurementId: 'G-RPVXHC6QYL',
  );

}